CREATE TABLE [dbo].[TaskTypes]
(
	[Id] TINYINT NOT NULL PRIMARY KEY IDENTITY ( 1, 1 )
	,TaskType NVARCHAR ( 50 ) NOT NULL
	,IsActive BIT NOT NULL CONSTRAINT DF_TaskTypes_IsActive DEFAULT ( 1 )
	,CreatedDate DATETIME NOT NULL CONSTRAINT DF_TaskTypes_CreatedDate DEFAULT ( GETDATE ( ) )
	,CreatedBy NVARCHAR ( 50 ) NOT NULL CONSTRAINT DF_TaskTypes_CreatedBy DEFAULT ( SYSTEM_USER )
	,UpdatedDate DATETIME NOT NULL CONSTRAINT DF_TaskTypes_UpdatedDate DEFAULT ( GETDATE ( ) )
	,UpdatedBy NVARCHAR ( 50 ) NOT NULL CONSTRAINT DF_TaskTypes_UpdatedBy DEFAULT ( SYSTEM_USER )
	,CONSTRAINT UK_TaskTypes_TaskStatus UNIQUE ( TaskType )
)
