//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wertigo.SunshineWebAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSchedule
    {
        public System.Guid Id { get; set; }
        public System.Guid TaskId { get; set; }
        public Nullable<short> FrequencyType { get; set; }
        public Nullable<short> FrequencyInterval { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public double Duration { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
